version: '3.8'

# volumes:
#   wp_data:
#   mysql_data:

# networks:
#   my_network:

services:
  # mariadb:
  #   build: ./requirements/mariadb
  #   container_name: mariadb
  #   restart: always
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - my_network

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   restart: always
  #   # depends_on:
  #   #   - mariadb
  #   volumes:
  #     - wp_data:/var/www/html
  #   networks:
  #     - my_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    # depends_on:
    #   - wordpress
    ports:
      - "8080:80"
    # networks:
    #   - my_network

