version: "3.8"

networks:
  mynetwork:

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/www/html
      o: bind

  mariadb_volume:    # CHANGED: renamed from db_volume
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/db
      o: bind

  nginx_logs:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/logs/nginx
      o: bind

secrets:
  ssl_private_key:
    file: requirements/nginx/keys/nginx-selfsigned.key

  ssl_certificate:
    file: requirements/nginx/keys/nginx-selfsigned.crt

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    env_file: .env
    networks:
      - mynetwork
    volumes:
      - mariadb_volume:/var/lib/mysql
      
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - mynetwork
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    networks:
      - mynetwork
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
      - nginx_logs:/var/log/nginx
    secrets:
      - ssl_private_key
      - ssl_certificate
